# Context Manifest: AWS Expert Agent
# Token budget: ~4000 tokens
# Purpose: AWS services, architecture, deployment, best practices

role: aws-agent
token_budget: 4000

# Files to always load
required:
  - STACK.md                            # Current infrastructure
  - CONTEXT_PACK.md                     # Architecture overview

# Files to load if available and budget permits
optional:
  - docs/AWS.md                         # AWS-specific docs
  - docs/INFRASTRUCTURE.md              # Infrastructure docs
  - cloudformation/                     # CloudFormation templates (listing)
  - cdk/                                # AWS CDK (listing)
  - sam/                                # SAM templates (listing)
  - terraform/                          # Terraform AWS resources (listing)
  - serverless.yml                      # Serverless framework

# Files to explicitly skip
exclude:
  - src/                                # Application code
  - tests/                              # Test code
  - docs/research/                      # Research not relevant

# Trigger patterns for auto-detection
triggers:
  - "AWS"
  - "Amazon"
  - "Lambda"
  - "S3"
  - "EC2"
  - "ECS"
  - "EKS"
  - "RDS"
  - "DynamoDB"
  - "CloudFormation"
  - "CDK"
  - "API Gateway"
  - "Cognito"
  - "SQS"
  - "SNS"

# AWS expertise areas
focus:
  - well_architected_framework
  - cost_optimization
  - security_best_practices
  - serverless_patterns
  - container_services
